Repository mezzio/mezzio-session, pull requests merged in 2024-08, with the labels that each got.

#61 Deprecated `SessionIdentifierAwareInterface` for removal in v2.0
  psalm-baseline.xml
  src/SessionIdentifierAwareInterface.php
Labels: Documentation, Feature Removal

#63 Moved `v1` documentation files from `docs/book` to `docs/book/v1/`
  docs/book/v1/installation.md
  docs/book/v1/intro.md
  docs/book/v1/middleware.md
  docs/book/v1/persistence.md
  docs/book/v1/session.md
  mkdocs.yml
Labels: Documentation

#65 Fix incorrect `mkdocs` configuration
  mkdocs.yml
Labels: Bug, Documentation

#66 Merge release 1.15.1 into 2.0.x
  docs/book/v1/installation.md
  docs/book/v1/intro.md
  docs/book/v1/middleware.md
  docs/book/v1/persistence.md
  docs/book/v1/session.md
  mkdocs.yml
Labels: Documentation

#68 `redirect_maps` should be a `dict`, not a list
  mkdocs.yml
Labels: Bug, Documentation

#70 Merge patch releases 1.15.2 and 1.15.3 into 2.0.x
  mkdocs.yml
Labels: Bug, Documentation

#71 Removed `SessionIdentifierAwareInterface`
  docs/book/v2/installation.md
  docs/book/v2/intro.md
  docs/book/v2/middleware.md
  docs/book/v2/persistence.md
  docs/book/v2/session.md
  mkdocs.yml
  psalm-baseline.xml
  src/LazySession.php
  src/Session.php
  src/SessionIdentifierAwareInterface.php
  src/SessionInterface.php
  src/SessionPersistenceInterface.php
  test/SessionTest.php
Labels: BC Break, Documentation, Enhancement
